apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mhjuw6mqs-go 
  janus-idp.io/tekton: mhjuw6mqs-go
  backstage.io/kubernetes-id: mhjuw6mqs-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mhjuw6mqs-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml