apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mhjuw6mqs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mhjuw6mqs-go 
  name: mhjuw6mqs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mhjuw6mqs-go 
